In [21]:
import pandas as pd

df_acquiring = pd.read_csv('./df_acquiring.csv')
df_acquired = pd.read_csv('./df_acquired.csv')
df_funding = pd.read_csv('./df_funding.csv')
df_ipo = pd.read_csv('./df_ipo.csv')

df_milestone = pd.read_csv("sentimented_milestone.csv")
df_ipo = pd.read_csv("cleaned_product.csv")

In [17]:
df_acquired

,acquired_object_id,AUD,CAD,EUR,GBP,JPY,SEK,USD,cash,cash_and_stock,stock,acquired_time_since_founded
0,c:22103,0,0,0,0,0,0,1,1,0,0,[18.]
1,c:54651,0,0,0,0,0,0,1,0,0,0,[29.]
2,c:159552,0,0,0,0,0,0,1,0,0,1,[31.]
3,c:329,0,0,0,0,0,0,1,0,0,0,[31.]
4,c:2315,0,0,0,0,0,0,1,0,0,0,[31.]
5,c:54405,0,0,0,0,0,0,1,0,0,0,[59.]
6,c:8565,0,0,0,0,0,0,1,0,0,0,[67.]
7,c:86,0,0,0,0,0,0,1,0,0,0,[67.]
8,c:45891,0,0,0,0,0,0,1,1,0,0,[75.]
9,c:193193,0,0,0,0,0,0,1,0,0,0,[86.]
10,c:192352,0,0,0,0,0,0,1,0,0,0,[90.]
11,c:681,0,0,0,0,0,0,1,1,0,0,[90.]
12,c:47111,0,0,0,0,0,0,1,1,0,0,[92.]
13,c:149002,0,0,0,0,0,0,1,0,0,0,[92.]
14,c:195841,0,0,0,0,0,0,1,0,0,0,[100.]
15,c:3306,0,0,0,0,0,0,1,1,0,0,[103.]
16,c:2370,0,0,0,0,0,0,1,0,1,0,[107.]
17,c:213362,0,0,0,0,0,0,1,0,0,0,[108.]
18,c:27053,0,0,0,0,0,0,1,0,0,0,[121.]
19,c:1229,0,0,0,0,0,0,1,0,1,0,[121.]
20,c:156584,0,0,0,0,0,0,1,0,0,0,[122.]
21,c:175581,0,0,0,0,0,0,1,0,0,0,[122.]
22,c:212610,0,0,0,0,0,0,1,0,0,0,[129.]
23,c:183206,0,0,0,0,0,0,1,0,0,1,[132.]
24,c:211517,0,0,0,0,0,0,1,0,0,0,[134.]
25,c:187849,0,0,0,0,0,0,1,0,0,0,[136.]
26,c:3138,0,0,0,0,0,0,1,0,0,0,[141.]
27,c:182466,0,0,0,0,0,0,1,0,0,0,[143.]
28,c:8652,0,0,0,0,0,0,1,1,0,0,[146.]
29,c:245790,0,0,0,0,0,0,1,0,0,0,[149.]
...,...,...,...,...,...,...,...,...,...,...,...,...
4802,c:30506,0,0,0,0,0,0,1,0,0,0,[24658.]
4803,c:269416,0,0,0,0,0,0,1,0,0,0,[24747.]
4804,c:38641,0,0,0,0,0,0,1,0,0,0,[24828.]
4805,c:242705,0,0,0,0,0,0,1,0,0,0,[26752.]
4806,c:216499,0,0,0,0,0,0,1,0,0,0,[27342.]
4807,c:25631,0,0,0,0,0,0,1,0,0,0,[27513.]
4808,c:32156,0,0,0,0,0,0,1,0,0,0,[28032.]
4809,c:29313,0,0,0,0,0,0,1,1,0,0,[28116.]
4810,c:267421,0,0,0,0,0,0,1,0,0,0,[28392.]
4811,c:5296,0,0,0,0,0,0,1,0,0,0,[29436.]
4812,c:34009,0,0,0,0,0,0,1,0,0,0,[29505.]
4813,c:2332,0,0,0,0,0,0,1,0,1,0,[29517.]
4814,c:51460,0,0,0,0,0,0,1,0,0,0,[29704.]
4815,c:81111,0,0,0,0,0,0,1,1,0,0,[30135.]
4816,c:86083,0,0,0,0,0,0,1,1,0,0,[30186.]
4817,c:10232,0,0,0,0,0,0,1,0,0,0,[30591.]
4818,c:270108,0,0,0,0,0,0,1,1,0,0,[30595.]
4819,c:220985,0,0,0,0,0,0,1,0,0,0,[30903.]
4820,c:58517,0,0,0,0,0,0,1,0,0,0,[30979.]
4821,c:7389,0,0,0,0,0,0,1,0,0,0,[31502.]
4822,c:25144,0,0,0,0,0,0,1,0,0,0,[32415.]
4823,c:241120,0,0,0,0,0,0,1,0,0,0,[33442.]
4824,c:256351,0,0,0,0,0,0,1,0,0,0,[33468.]
4825,c:271047,0,0,0,0,0,0,1,0,0,0,[33520.]
4826,c:256435,0,0,0,0,0,0,1,0,0,0,[34564.]
4827,c:4988,0,0,0,0,0,0,1,0,0,0,[35685.]
4828,c:34088,0,0,0,0,0,0,1,0,0,0,[36326.]
4829,c:26287,0,0,0,0,0,0,1,0,0,0,[36591.]
4830,c:277231,0,0,0,0,0,0,1,0,0,1,[39754.]
4831,c:213995,0,0,0,0,0,0,1,0,0,0,[40318.]

In [18]:
df_acquiring

,acquiring_object_id,acquired_object_id,price_amount,AUD,CAD,EUR,GBP,JPY,SEK,USD,cash,cash_and_stock,stock,acquiring_time_since_founded
0,c:260783,c:80142,2.406487e+08,0,0,0,0,0,0,1,0,0,0,[1.]
1,c:307,c:306,2.393940e+08,0,0,0,0,0,0,1,1,0,0,[6.]
2,c:60326,c:146208,1.000000e+06,0,0,0,0,0,0,1,0,0,1,[14.]
3,c:15461,c:15460,7.000000e+04,0,0,0,0,0,0,1,1,0,0,[25.]
4,c:192899,c:193355,3.300000e+05,0,0,0,0,0,0,1,0,1,0,[27.]
5,c:138299,c:141275,1.500000e+04,0,0,0,0,0,0,1,1,0,0,[29.]
6,c:80259,c:4716,2.406487e+08,0,0,0,0,0,0,1,0,0,0,[31.]
7,c:166448,c:40101,2.128162e+08,0,0,0,0,0,0,1,0,0,0,[31.]
8,c:82144,c:60638,3.415096e+08,0,0,0,0,0,0,1,0,0,0,[39.]
9,c:5457,c:5456,5.000000e+03,0,0,0,0,0,0,1,1,0,0,[41.]
10,c:64703,c:59456,3.835849e+08,0,0,0,0,0,0,1,0,0,0,[41.]
11,c:195859,c:195858,1.000000e+05,0,0,0,0,0,0,1,1,0,0,[42.]
12,c:221698,c:190514,5.000000e+03,0,0,0,0,0,0,1,1,0,0,[45.]
13,c:171432,c:44839,3.000000e+03,0,0,0,0,0,0,1,0,1,0,[49.]
14,c:47470,c:23476,4.061496e+08,0,0,0,0,0,0,1,0,0,0,[59.]
15,c:23010,c:110,2.945954e+08,0,0,0,0,0,0,1,0,0,1,[59.]
16,c:279935,c:169569,2.406487e+08,0,0,0,0,0,0,1,0,0,0,[61.]
17,c:85143,c:47064,2.406487e+08,0,0,0,0,0,0,1,0,0,0,[61.]
18,c:207479,c:150485,2.945954e+08,0,0,0,0,0,0,1,0,0,0,[61.]
19,c:15180,c:5783,3.028942e+08,0,0,0,0,0,0,1,0,0,0,[71.]
20,c:190559,c:38003,2.945954e+08,0,0,0,0,0,0,1,0,0,0,[75.]
21,c:84204,c:43263,2.945954e+08,0,0,0,0,0,0,1,0,0,0,[75.]
22,c:45891,c:45891,2.945954e+08,0,0,0,0,0,0,1,1,0,0,[75.]
23,c:175916,c:25200,2.945954e+08,0,0,0,0,0,0,1,0,0,0,[78.]
24,c:64703,c:71792,5.860520e+08,0,0,0,0,0,0,1,0,0,0,[78.]
25,c:193054,c:42069,2.406487e+08,0,0,0,0,0,0,1,0,1,0,[82.]
26,c:45772,c:45773,2.945954e+08,0,0,0,0,0,0,1,0,1,0,[91.]
27,c:257213,c:116092,4.061496e+08,0,0,0,0,0,0,1,0,0,0,[91.]
28,c:176998,c:163003,2.945954e+08,0,0,0,0,0,0,1,0,0,0,[92.]
29,c:150328,c:25307,2.406487e+08,0,0,0,0,0,0,1,0,1,0,[92.]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4100,c:83647,c:28502,2.660000e+08,0,0,0,0,0,0,1,0,0,0,[35525.]
4101,c:26486,c:3445,2.770000e+07,0,0,0,0,0,0,1,0,0,0,[35585.]
4102,c:26486,c:3525,2.700000e+07,0,0,0,0,0,0,1,0,0,0,[36000.]
4103,c:7060,c:50055,5.400000e+07,0,0,0,0,0,0,1,0,0,0,[36800.]
4104,c:31279,c:31278,9.830000e+07,0,0,0,0,0,0,1,0,0,0,[37085.]
4105,c:1246,c:596,4.500000e+07,0,0,0,0,0,0,1,1,0,0,[37163.]
4106,c:20211,c:26091,4.061496e+08,0,0,0,0,0,0,1,0,0,0,[37255.]
4107,c:15446,c:153534,7.059124e+08,0,0,0,0,0,0,1,0,0,0,[37344.]
4108,c:59312,c:228074,1.950000e+08,0,0,0,0,0,0,1,0,0,0,[37425.]
4109,c:31357,c:32180,1.750000e+08,0,0,0,0,0,0,1,0,0,0,[37725.]
4110,c:259799,c:183726,3.040000e+07,0,0,0,0,0,0,1,0,0,0,[37861.]
4111,c:7060,c:25775,5.750000e+09,0,0,0,0,0,0,1,0,1,0,[37891.]
4112,c:276618,c:276620,6.400000e+07,0,0,0,0,0,0,1,0,0,0,[37925.]
4113,c:44898,c:141919,7.250000e+07,0,0,0,0,0,0,1,1,0,0,[37938.]
4114,c:31357,c:31356,6.287000e+07,0,0,0,0,0,0,1,0,0,0,[37949.]
4115,c:20211,c:35403,9.500000e+07,0,0,0,0,0,0,1,1,0,0,[38274.]
4116,c:4199,c:6833,2.647311e+08,0,0,0,0,0,0,1,0,0,0,[38360.]
4117,c:14011,c:3455,2.647311e+08,0,0,0,0,0,0,1,1,0,0,[38441.]
4118,c:7060,c:77348,4.061496e+08,0,0,0,0,0,0,1,0,0,0,[38495.]
4119,c:157985,c:198069,5.480000e+07,0,0,0,0,0,0,1,0,1,0,[38665.]
4120,c:261784,c:69808,1.250000e+09,0,0,0,0,0,0,1,0,0,0,[38964.]
4121,c:7060,c:31310,2.406487e+08,0,0,0,0,0,0,1,0,0,0,[39237.]
4122,c:4199,c:12208,3.835849e+08,0,0,0,0,0,0,1,0,0,0,[39640.]
4123,c:20211,c:55583,2.300000e+08,0,0,0,0,0,0,1,1,0,0,[39689.]
4124,c:57396,c:57393,7.779535e+08,0,0,0,0,0,0,1,0,0,0,[39711.]
4125,c:4199,c:12440,4.000000e+06,0,0,0,0,0,0,1,0,0,0,[39793.]
4126,c:4199,c:15491,1.750000e+08,0,0,0,0,0,0,1,0,0,0,[40201.]
4127,c:29929,c:23052,2.700000e+08,0,0,0,0,0,0,1,0,0,1,[40224.]
4128,c:11318,c:239331,9.000000e+06,0,0,0,0,0,0,1,0,0,0,[40280.]
4129,c:285396,c:285399,2.300000e+07,0,0,0,0,0,0,1,0,0,0,[40520.]

In [19]:
df_funding

,Unnamed: 0,object_id,funding_round_code,raised_amount_usd,participants,a,angel,b,c,d,e,f,g,seed,time_since_founded
0,16944,c:144040,seed,1.000000e+06,0,0,0,0,0,0,0,0,0,1,0
1,4093,c:18038,a,1.335000e+07,4,1,0,0,0,0,0,0,0,0,0
2,19165,c:161452,seed,8.660326e+05,0,0,0,0,0,0,0,0,0,1,0
3,19166,c:161453,seed,1.000000e+05,0,0,0,0,0,0,0,0,0,1,0
4,19169,c:161480,angel,2.500000e+05,1,0,1,0,0,0,0,0,0,0,0
5,28530,c:264245,angel,8.320994e+05,1,0,1,0,0,0,0,0,0,0,0
6,4121,c:18202,seed,4.250000e+05,2,0,0,0,0,0,0,0,0,1,0
7,19187,c:51578,angel,6.958500e+05,0,0,1,0,0,0,0,0,0,0,0
8,19191,c:161699,seed,5.750000e+05,1,0,0,0,0,0,0,0,0,1,0
9,19212,c:161944,angel,1.000000e+06,5,0,1,0,0,0,0,0,0,0,0
10,4145,c:4299,seed,1.000000e+06,0,0,0,0,0,0,0,0,0,1,0
11,28502,c:263989,seed,6.500000e+05,0,0,0,0,0,0,0,0,0,1,0
12,13601,c:68549,seed,5.000000e+04,0,0,0,0,0,0,0,0,0,1,0
13,13592,c:68486,angel,8.320994e+05,0,0,1,0,0,0,0,0,0,0,0
14,13587,c:68442,seed,8.660326e+05,1,0,0,0,0,0,0,0,0,1,0
15,19232,c:162067,seed,1.000000e+03,0,0,0,0,0,0,0,0,0,1,0
16,4184,c:18701,seed,1.000000e+05,0,0,0,0,0,0,0,0,0,1,0
17,4188,c:18741,angel,2.797200e+05,6,0,1,0,0,0,0,0,0,0,0
18,28549,c:264553,seed,2.500000e+05,0,0,0,0,0,0,0,0,0,1,0
19,13574,c:68329,angel,2.000000e+05,0,0,1,0,0,0,0,0,0,0,0
20,19162,c:45196,seed,1.431400e+05,1,0,0,0,0,0,0,0,0,1,0
21,13671,c:69063,seed,8.660326e+05,0,0,0,0,0,0,0,0,0,1,0
22,28705,c:265497,seed,8.660326e+05,0,0,0,0,0,0,0,0,0,1,0
23,19125,c:161240,seed,1.500000e+06,0,0,0,0,0,0,0,0,0,1,0
24,28693,c:265463,seed,5.000000e+04,0,0,0,0,0,0,0,0,0,1,0
25,13719,c:64996,seed,1.150000e+06,1,0,0,0,0,0,0,0,0,1,0
26,4009,c:17758,a,4.000000e+06,1,1,0,0,0,0,0,0,0,0,0
27,28677,c:265370,seed,5.000000e+04,0,0,0,0,0,0,0,0,0,1,0
28,13714,c:69596,seed,2.000000e+05,0,0,0,0,0,0,0,0,0,1,0
29,28661,c:265241,seed,8.660326e+05,1,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25824,29328,c:145945,seed,1.000000e+06,0,0,0,0,0,0,0,0,0,1,13058
25825,12466,c:59556,a,6.852076e+06,1,1,0,0,0,0,0,0,0,0,13076
25826,24552,c:220572,seed,1.158000e+06,0,0,0,0,0,0,0,0,0,1,13235
25827,26876,c:243852,seed,5.000000e+05,0,0,0,0,0,0,0,0,0,1,13360
25828,24374,c:69136,seed,8.660326e+05,0,0,0,0,0,0,0,0,0,1,13880
25829,24048,c:212776,a,1.200000e+07,1,1,0,0,0,0,0,0,0,0,14016
25830,26981,c:244910,seed,7.250000e+05,0,0,0,0,0,0,0,0,0,1,14093
25831,26656,c:16243,seed,1.278900e+05,0,0,0,0,0,0,0,0,0,1,14122
25832,30599,c:277196,seed,8.600000e+04,0,0,0,0,0,0,0,0,0,1,14180
25833,2369,c:6713,b,1.175000e+07,3,0,0,1,0,0,0,0,0,0,14209
25834,27021,c:245323,a,5.000000e+04,0,1,0,0,0,0,0,0,0,0,14438
25835,7110,c:35691,a,6.000000e+06,0,1,0,0,0,0,0,0,0,0,14883
25836,24472,c:219131,seed,4.312000e+04,0,0,0,0,0,0,0,0,0,1,15442
25837,29135,c:267819,seed,1.800000e+06,0,0,0,0,0,0,0,0,0,1,15596
25838,25550,c:177075,seed,1.000000e+06,0,0,0,0,0,0,0,0,0,1,15869
25839,24530,c:177075,seed,6.750000e+05,0,0,0,0,0,0,0,0,0,1,16220
25840,17041,c:144811,a,1.000000e+07,1,1,0,0,0,0,0,0,0,0,16420
25841,11723,c:36848,d,6.500000e+07,3,0,0,0,0,1,0,0,0,0,17418
25842,24769,c:164565,seed,5.000000e+05,0,0,0,0,0,0,0,0,0,1,19516
25843,30822,c:279000,a,2.500000e+07,5,1,0,0,0,0,0,0,0,0,20039
25844,12601,c:8261,c,2.000000e+06,2,0,0,0,1,0,0,0,0,0,20817
25845,25889,c:236502,seed,2.000000e+05,0,0,0,0,0,0,0,0,0,1,21739
25846,29459,c:269551,seed,4.889080e+06,1,0,0,0,0,0,0,0,0,1,21826
25847,28140,c:34590,b,1.000000e+07,1,0,0,1,0,0,0,0,0,0,21907
25848,8468,c:42841,a,1.000000e+07,3,1,0,0,0,0,0,0,0,0,21946
25849,5559,c:25993,b,6.530000e+06,1,0,0,1,0,0,0,0,0,0,24135
25850,29782,c:4304,b,1.000000e+07,1,0,0,1,0,0,0,0,0,0,27606
25851,29783,c:4304,c,1.000000e+07,2,0,0,0,1,0,0,0,0,0,28257
25852,28872,c:266692,seed,9.531830e+05,0,0,0,0,0,0,0,0,0,1,32439
25853,25060,c:228200,a,2.060000e+08,0,1,0,0,0,0,0,0,0,0,33401

In [20]:
df_ipo

     Unnamed: 0 object_id time_since_founded
0            27    c:4495                [1]
1           908  c:144059               [67]
2            11     c:475               [83]
3           198   c:10614              [121]
4           806  c:164413              [324]
5           691  c:145411              [340]
6          1224  c:281988              [694]
7          1253  c:235945              [711]
8           716   c:48759              [754]
9           611   c:22130              [896]
10          973  c:245010              [947]
11         1017  c:258641              [968]
12         1094  c:265792              [992]
13          309    c:1368             [1018]
14          229   c:37881             [1081]
15          681   c:11391             [1107]
16          709   c:24982             [1168]
17           15     c:108             [1197]
18          658   c:40482             [1253]
19          957  c:241173             [1301]
20          963   c:46007             [1306]
21         1034  c:258957             [1334]
22          867   c:37431             [1409]
23         1214   c:37940             [1414]
24          486    c:1448             [1448]
25           65   c:15609             [1476]
26          308   c:43666             [1531]
27          936   c:38270             [1598]
28          344    c:1249             [1636]
29          699    c:1812             [1695]
..          ...       ...                ...
675         124     c:355            [25776]
676         508   c:64802            [26290]
677         259   c:39278            [27400]
678         727   c:34406            [27493]
679         431   c:58207            [27672]
680         216   c:37380            [27738]
681        1250   c:39330            [28470]
682         584    c:4304            [29679]
683         646   c:30927            [29811]
684        1229  c:223939            [29915]
685         753    c:1915            [30787]
686           2     c:342            [30797]
687         414   c:20016            [30933]
688        1163  c:274050            [31708]
689         428    c:7576            [32233]
690         166   c:34181            [32433]
691         537     c:541            [32533]
692          14    c:3658            [33323]
693         140   c:32510            [33504]
694        1246  c:258527            [33947]
695         550   c:30981            [34009]
696        1225   c:27295            [34662]
697         987   c:57929            [35654]
698        1022   c:26486            [36033]
699         746   c:59312            [36993]
700         710    c:7060            [38791]
701         367    c:4199            [39642]
702        1109   c:11318            [40280]
703         935   c:70725            [40374]
704        1027   c:20211            [40781]

[705 rows x 3 columns]

In [22]:
df_milestone

,Unnamed: 0,Unnamed: 0.1,object_id,milestone_at,description,embedding,company_found_at,since_founded,neg,compound,neu,pos
0,0,0,c:12,2008-06-09,Survives iPhone 3G Stevenote,"(2.44244, -0.367023, 2.753441, 2.0842850000000...",2006-03-21,811,0.000,0.0000,1.000,0.000
1,1,2,c:59,2008-06-18,More than 4 Billion videos viewed at Google Si...,"(4.51213, 0.9792995999999998, 10.63374, 4.9890...",1998-09-07,3572,0.000,0.0000,1.000,0.000
2,2,3,c:314,2008-06-18,Reddit goes Open Source,"(0.43957900000000005, 1.59626, 0.105294, 2.119...",2005-01-01,1264,0.000,0.0000,1.000,0.000
3,3,4,c:314,2008-01-22,Adds the ability to create your own Reddits,"(0.88915, 0.758532, 1.00371, 0.810659999999999...",2005-01-01,1116,0.000,0.5267,0.577,0.423
4,4,5,c:283,2008-06-18,"Adobe announced new content from MTV Networks,...","(-0.07670670000000057, 6.456332599999999, 10.8...",1982-12-01,9331,0.000,0.3612,0.940,0.060
5,5,6,c:6816,2008-02-01,Closed release of first prototype,"(0.9780636, -0.539113, 1.11254, 1.045648000000...",2007-01-01,396,0.000,0.0000,1.000,0.000
6,6,7,c:6816,2008-05-01,Closed release of second prototype,"(0.8216536, -0.669503, 1.5119120000000001, 1.4...",2007-01-01,486,0.000,0.0000,1.000,0.000
7,7,8,c:5874,2008-06-19,"Scoofers, a new search engine that combines se...","(6.609258, 0.16013, 5.129558899999999, 3.70037...",2006-01-01,900,0.000,0.5106,0.830,0.170
8,8,9,c:2034,2008-07-01,Jeremy Zawodny leaves Yahoo for Craigslist.,"(2.7166300000000003, 0.1055299999999999, 1.486...",1995-03-01,4871,0.000,0.0000,1.000,0.000
9,9,10,c:5085,2008-04-23,SnapLogic releases professional versions of da...,"(2.037153, -1.419894, 6.44378, 1.8828500000000...",2006-01-01,843,0.000,0.4019,0.838,0.162
10,10,11,c:1388,2011-02-06,AOL Acquires Huffington Post,"(1.36614, -0.36575199999999997, 3.36001, 1.728...",2005-05-09,2099,0.000,0.0000,1.000,0.000
11,11,12,c:75,2008-06-19,Joshua Schachter resigns from the company he s...,"(-0.73754, -0.8689930000000001, 0.153603699999...",2003-09-01,1753,0.247,-0.3182,0.753,0.000
12,12,13,c:6947,2008-05-15,Bevy Launches,"(1.23189, -0.070434, 0.52102, 0.865173, -1.267...",2007-09-27,231,0.000,0.0000,1.000,0.000
13,13,14,c:12,2008-06-09,Twitter partners with Summize to cover Apple n...,"(1.8672900000000001, 0.8070100000000002, 2.914...",2006-03-21,811,0.000,0.0000,1.000,0.000
14,14,15,c:12,2008-05-28,Launches a status blog to communicate to users...,"(1.46831, 1.53718, 3.8613200000000005, 1.81783...",2006-03-21,799,0.000,0.4404,0.805,0.195
15,15,16,c:12,2008-05-07,Twitter Starts Blacklisting Spammers,"(0.7795269999999999, -1.55193, 2.48881, 0.5273...",2006-03-21,778,0.464,-0.3818,0.536,0.000
16,16,17,c:12,2008-04-24,VP Lee Mighdoll Leaves Twitter,"(-0.044680000000000164, 2.68738, 2.581021, 1.9...",2006-03-21,765,0.000,0.0000,1.000,0.000
17,17,18,c:12,2008-04-23,Chief Architect Blaine Cook Leaves Twitter,"(1.4898699999999998, 2.014611, 0.3224109999999...",2006-03-21,764,0.000,0.0000,1.000,0.000
18,18,19,c:12,2008-04-22,Twitter Japan Launches,"(1.3042399999999998, -0.13802, 2.61054, 2.3082...",2006-03-21,763,0.000,0.0000,1.000,0.000
19,19,20,c:12,2008-04-16,Twitter helps bust American man out of Egyptia...,"(0.54464, 2.567883, 1.2358199999999997, -1.439...",2006-03-21,757,0.000,0.3818,0.755,0.245
20,20,21,c:3515,2007-09-01,Closed Seed Financing,"(0.8222236, -0.612834, 1.18322, 1.62013, 0.122...",2007-01-01,243,0.000,0.0000,1.000,0.000
21,21,22,c:3515,2007-10-15,Launched first game,"(-0.18806999999999996, -0.2803800000000001, -0...",2007-01-01,287,0.000,0.1280,0.571,0.429
22,22,23,c:5411,2008-06-03,Sometrics has introduced an ad-serving platfor...,"(4.183873599999999, 2.9900386, 10.140687, 7.53...",2007-09-01,276,0.000,0.2500,0.943,0.057
23,23,24,c:2391,2008-06-01,Appeared in TIME magazine's list of \50 Best W...,"(-2.388878, 2.75261, 2.990243, 0.4074200000000...",2007-03-12,447,0.000,0.6369,0.704,0.296
24,24,25,c:6501,2008-06-21,Released Who-Im. The First Instant Messenger f...,"(0.6192619999999999, 1.65884, 5.08412, 3.28154...",2007-11-03,231,0.000,0.0000,1.000,0.000
25,25,26,c:4068,2008-04-01,Recognised by Webby Awards as Official Webby H...,"(-5.530805, 6.036709999999999, -1.957433999999...",2004-12-30,1188,0.000,0.7269,0.596,0.404
26,26,27,c:1972,2008-06-23,Salesforce releases new force.com toolkit for ...,"(5.08081, -1.7988, 4.338795900000001, 4.081654...",1999-01-01,3461,0.000,0.0000,1.000,0.000
27,27,28,c:5149,2007-10-22,ExpertFlyer releases a Mobile edition at mobil...,"(1.1148099999999999, -0.10543000000000002, 4.6...",2004-03-05,1326,0.000,0.0000,1.000,0.000
28,28,29,c:5149,2008-04-04,ExpertFlyer.com announces the availablity of i...,"(0.06486800000000009, 2.302635, 2.769266, 2.03...",2004-03-05,1491,0.000,0.5423,0.720,0.280
29,29,32,c:1298,2008-04-18,Dipity launched,"(0.86323, -0.52353, 0.47888, 0.27485, -0.90868...",2007-04-12,372,0.000,0.1280,0.400,0.600
...,...,...,...,...,...,...,...,...,...,...,...,...
22893,22893,39390,c:190997,2013-12-11,See a dramatic change in your skin with Lift a...,"(-2.492651, 3.0454090600000003, 0.865012999999...",1979-01-01,12763,0.000,0.0000,1.000,0.000
22894,22894,39392,c:36508,2013-12-11,"Globis, Intel-backed V-Cube raises $43m in Tok...","(1.4360300000000001, -0.38495999999999986, 4.9...",1998-10-01,5550,0.000,0.0000,1.000,0.000
22895,22895,39394,c:63221,2012-05-20,Gruvi launches a rich media tool set for the p...,"(1.5800385999999997, 2.255589, -1.139089999999...",2010-08-01,658,0.000,0.8126,0.697,0.303
22896,22896,39395,c:63221,2012-12-01,Extending its platform to cover web and other ...,"(4.827513, 1.8217700000000003, 2.9422600000000...",2010-08-01,853,0.000,0.0000,1.000,0.000
22897,22897,39396,c:63221,2013-10-01,"Extending its platform further into Youtube, r...","(2.1479021999999994, 4.0854134, 4.085459999999...",2010-08-01,1157,0.000,0.5574,0.854,0.146
22898,22898,39397,c:177209,2013-09-02,JustGo received $450k in Seed funding from Fre...,"(4.084595, 1.483651, 1.6732859, 1.620237, 0.03...",2011-11-01,671,0.000,0.0000,1.000,0.000
22899,22899,39399,c:104151,2012-12-10,Deployed Re-engagement unit,"(2.90226, -1.63327, 1.04273, -0.26658800000000...",2003-01-01,3631,0.000,0.0000,1.000,0.000
22900,22900,39400,c:284350,2013-12-11,First round of funding: $450.000 by Investion,"(1.07348, 1.3562809999999998, 3.42739, -0.9291...",2013-01-01,344,0.000,0.0000,1.000,0.000
22901,22901,39401,c:229061,2013-10-31,Every1Mobile is named one of the UK?s most exc...,"(1.275967, 1.1833399999999996, -0.578176100000...",2010-01-01,1399,0.000,0.7688,0.623,0.377
22902,22902,39402,c:229061,2013-07-01,"Tech news site, Mashable, has ranked Every1Mob...","(-5.418508, 3.3314170000000005, 6.192801999999...",2010-01-01,1277,0.116,-0.1027,0.789,0.095
22903,22903,39405,c:169775,2013-12-11,Quandl surpasses 8 million dataset mark.,"(0.15603999999999996, 1.822138, 4.2885, -0.089...",2011-09-01,832,0.000,0.0000,1.000,0.000
22904,22904,39407,c:70134,2013-12-11,Manilla Expands Into Healthcare,"(0.056249999999999994, -0.548643, 0.7595891, 0...",2010-01-01,1440,0.000,0.1027,0.682,0.318
22905,22905,39408,c:70134,2013-12-04,Manilla Named to Kiplinger's Personal Finance'...,"(-2.9263809999999992, 3.25645, 1.2090543200000...",2010-01-01,1433,0.000,0.6369,0.704,0.296
22906,22906,39409,c:35493,2013-12-11,Rdio Launches In 20 New Countries,"(1.161035, 0.7815300000000001, 1.3696089, 0.43...",2008-08-01,1958,0.000,0.0000,1.000,0.000
22907,22907,39412,c:157979,2013-10-23,World?s Largest Fit Database,"(1.09455, 0.4589499999999999, 1.02117, 2.72346...",2006-01-01,2852,0.000,0.3612,0.545,0.455
22908,22908,39413,c:157979,2013-01-01,"1,000+ Top Brand Data Partners","(0.7369300000000001, 2.30485, 4.69335000000000...",2006-01-01,2557,0.000,0.2023,0.690,0.310
22909,22909,39414,c:157979,2013-01-01,"Powering fit for top retailers like Nordstrom,...","(-0.8178529999999999, 0.002519999999999911, 1....",2006-01-01,2557,0.000,0.7003,0.638,0.362
22910,22910,39415,c:157979,2013-01-01,Six times conversion rate increases are seen f...,"(0.5549700000000001, 1.5275699999999999, 2.426...",2006-01-01,2557,0.000,0.0000,1.000,0.000
22911,22911,39416,c:166739,2013-12-11,Instacart Launches in Boston,"(0.91126, 0.75553, 0.43033000000000005, 0.7765...",2012-07-01,528,0.000,0.0000,1.000,0.000
22912,22912,39417,c:166739,2013-09-17,Instacart Launches in Chicago,"(0.23300999999999994, 0.73889, 0.4019000000000...",2012-07-01,443,0.000,0.0000,1.000,0.000
22913,22913,39421,c:189582,2013-12-11,"Received $225,000 STTR grant from the National...","(-1.827665, 4.84948, 2.1946882999999997, -0.11...",2011-08-09,855,0.000,0.3612,0.762,0.238
22914,22914,39423,c:63800,2014-01-01,Fisherman's Friend conducts 250.000? campaign ...,"(2.7473891999999998, 1.630715, 2.223318, -0.90...",2012-10-31,427,0.000,0.4939,0.652,0.348
22915,22915,39435,c:285948,2013-12-11,Port of Grays Harbor buys NewWood assets for $...,"(2.25223, 2.7177540000000002, 0.89924000000000...",1911-01-01,37600,0.000,0.1779,0.825,0.175
22916,22916,39436,c:270027,2013-12-11,Florida Institute Provides Seed Funding to Par...,"(-0.1415200000000001, 1.969016, 0.789476000000...",2013-01-01,344,0.000,0.0000,1.000,0.000
22917,22917,39437,c:22725,2013-12-11,"OPEN SUBMISSIONS: Soul, Left-Field, Electronic...","(-3.3258430000000008, 8.391232, 9.188373, 8.26...",2008-03-07,2105,0.000,0.0000,1.000,0.000
22918,22918,39438,c:285950,2013-12-11,\r\\r\r\nCrealta Pharmaceuticals Buys Savient ...,"(2.24506, -0.16880600000000023, 2.02501, 1.667...",2013-08-01,132,0.000,0.1779,0.779,0.221
22919,22919,39443,c:38752,2013-12-11,Agios gets $20M from Celgene to extend cancer ...,"(6.605658, 0.805098, 0.5605800000000001, 1.096...",2008-01-01,2171,0.270,-0.1280,0.429,0.301
22920,22920,39445,c:82091,2013-11-20,Umeng was acquired by Alibaba.,"(1.45093, -0.39305, 0.8694999999999999, 2.0020...",2010-04-01,1329,0.000,0.0000,1.000,0.000
22921,22921,39450,c:60389,2013-07-10,ROCKETHOME received growth capital in a Series...,"(7.072540999999999, 2.5487120000000005, 10.908...",2010-06-01,1135,0.000,0.3818,0.909,0.091
22922,22922,39452,c:59519,2013-12-12,miiCard builds on recent momentum and vision f...,"(3.696647, 2.941404, 1.5729229, 3.009087999999...",2010-01-01,1441,0.000,0.2500,0.882,0.118

In [23]:
df_ipo

,id,parent_id,normalized_name,founded_at,status,alpha,beta,closed,development,live,operating,private
0,r:1,c:1,wikison wetpaint,2006-06-01,live,0,0,0,0,1,0,0
1,r:10,c:16,slacker web player,2007-06-05,operating,0,0,0,0,0,1,0
2,r:100,c:1585,vemo enterprise workforce planning,2008-07-01,live,0,0,0,0,1,0,0
3,r:10002,c:14171,dexmo study and revision network,2006-09-01,operating,0,0,0,0,0,1,0
4,r:10006,c:14180,shared hosting,2000-01-08,operating,0,0,0,0,0,1,0
5,r:10007,c:14180,vps hosting,2000-01-08,operating,0,0,0,0,0,1,0
6,r:10008,c:14180,managed services,2000-01-08,operating,0,0,0,0,0,1,0
7,r:10009,c:14184,hirebridge recruiter,2000-01-01,operating,0,0,0,0,0,1,0
8,r:10013,c:14187,competitive intelligence consulting and research,2001-01-01,operating,0,0,0,0,0,1,0
9,r:10014,c:6268,jumpstart,1989-01-01,live,0,0,0,0,1,0,0
10,r:10015,c:14198,office space rental,2009-01-01,operating,0,0,0,0,0,1,0
11,r:10016,c:14198,meeting room rental,2009-01-01,operating,0,0,0,0,0,1,0
12,r:10018,c:14201,feedmyapp,2007-06-05,live,0,0,0,0,1,0,0
13,r:10019,c:14201,professional on the web,2005-01-01,beta,0,1,0,0,0,0,0
14,r:10022,c:14202,win4lin,2006-01-01,operating,0,0,0,0,0,1,0
15,r:10025,c:14202,verde,2013-10-01,live,0,0,0,0,1,0,0
16,r:10026,c:14209,prowebsurfer c no evil plug in,2006-01-01,operating,0,0,0,0,0,1,0
17,r:10027,c:14209,prowebsurfer web service,2006-01-01,operating,0,0,0,0,0,1,0
18,r:10028,c:14215,conferenceedge communications suite,2008-01-01,live,0,0,0,0,1,0,0
19,r:10029,c:14216,asigra televaulting,2002-05-01,operating,0,0,0,0,0,1,0
20,r:10030,c:14216,funambol,2002-05-01,operating,0,0,0,0,0,1,0
21,r:10031,c:14218,the brand integration service,2007-01-01,operating,0,0,0,0,0,1,0
22,r:10032,c:14219,makeover men,2008-06-30,operating,0,0,0,0,0,1,0
23,r:10033,c:14219,makeover women,2008-06-30,operating,0,0,0,0,0,1,0
24,r:10034,c:14219,makeover couples,2008-06-30,operating,0,0,0,0,0,1,0
25,r:10035,c:2972,gameriot,2007-01-01,operating,0,0,0,0,0,1,0
26,r:10036,c:13174,authorstream,2007-04-02,live,0,0,0,0,1,0,0
27,r:10037,c:14221,wiziq,2007-04-02,live,0,0,0,0,1,0,0
28,r:10039,c:14227,fileride,2008-10-31,beta,0,1,0,0,0,0,0
29,r:1004,c:1170,collegehumor,1999-01-01,live,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
22949,r:9956,c:4172,nestoria deutschland,2006-02-16,operating,0,0,0,0,0,1,0
22950,r:9957,c:14108,jrebel,2007-09-07,operating,0,0,0,0,0,1,0
22951,r:9958,c:14115,dezidr,2007-03-03,operating,0,0,0,0,0,1,0
22952,r:9959,c:4630,knowledge plaza,2008-10-01,live,0,0,0,0,1,0,0
22953,r:9965,c:14119,roxen editorial portal,1994-01-01,operating,0,0,0,0,0,1,0
22954,r:9966,c:14119,roxen cms,1994-01-01,operating,0,0,0,0,0,1,0
22955,r:9967,c:14121,dreamface 2 0,2007-03-15,live,0,0,0,0,1,0,0
22956,r:9968,c:14122,blaisic,2008-07-07,operating,0,0,0,0,0,1,0
22957,r:9969,c:14123,firebirdcms,2006-01-01,operating,0,0,0,0,0,1,0
22958,r:997,c:1164,nutrition advisors network,2008-01-01,operating,0,0,0,0,0,1,0
22959,r:9971,c:14132,vamooz,2008-11-27,beta,0,1,0,0,0,0,0
22960,r:9972,c:14134,publicity generating service,2004-06-01,operating,0,0,0,0,0,1,0
22961,r:9973,c:14140,homethinking realtor search,2005-12-01,operating,0,0,0,0,0,1,0
22962,r:9974,c:14140,homethinking neighborhoods,2005-12-01,operating,0,0,0,0,0,1,0
22963,r:9975,c:14140,homethinking mortgage,2005-12-01,operating,0,0,0,0,0,1,0
22964,r:9976,c:14141,pintarget,2009-08-01,live,0,0,0,0,1,0,0
22965,r:9977,c:14144,momail mobile email,2005-01-01,operating,0,0,0,0,0,1,0
22966,r:9978,c:14145,lumoflow,2008-01-01,live,0,0,0,0,1,0,0
22967,r:998,c:1164,tech advisors network,2007-12-30,operating,0,0,0,0,0,1,0
22968,r:9982,c:14151,timesheet management software,1999-12-01,operating,0,0,0,0,0,1,0
22969,r:9987,c:12842,sports blog network,2008-10-01,operating,0,0,0,0,0,1,0
22970,r:9991,c:14155,ad campaign visibility,2008-08-01,live,0,0,0,0,1,0,0
22971,r:9992,c:14155,ad inventory visibility,2007-01-01,operating,0,0,0,0,0,1,0
22972,r:9993,c:14156,pomelotv,2007-03-07,operating,0,0,0,0,0,1,0
22973,r:9994,c:14164,ciq membership,2002-01-15,operating,0,0,0,0,0,1,0
22974,r:9995,c:14164,sitelink listing feed for brokerages,2002-01-15,operating,0,0,0,0,0,1,0
22975,r:9996,c:14164,edclink listing feed for economic development ...,2002-01-15,operating,0,0,0,0,0,1,0
22976,r:9997,c:14164,cmail broadcast email marketing,2002-01-15,operating,0,0,0,0,0,1,0
22977,r:9998,c:14164,catylistcrm contact database,2002-01-15,operating,0,0,0,0,0,1,0
22978,r:9999,c:14164,catylist custom print web design,2002-01-15,operating,0,0,0,0,0,1,0