In [1]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
data_path = "../cb_db_csv/"
relatioinship_file_name = "cb_relationships.csv"
object_file_name = "cb_objects.csv"

/Users/Abby/anaconda3/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

In [2]:
def normalize(x):
    x = x.values.reshape(-1, 1)
    min_max_scaler = preprocessing.MinMaxScaler()
    x_scaled = min_max_scaler.fit_transform(x)
    return x_scaled

In [3]:
df_relationship = pd.read_csv(data_path + relatioinship_file_name, encoding = "ISO-8859-1",low_memory=False)
df_relationship = df_relationship.iloc[:,[2,3,8]]
df_relationship

,person_object_id,relationship_object_id,title
0,p:2,c:1,Co-Founder/CEO/Board of Directors
1,p:3,c:1,VP Marketing
2,p:4,c:3,Evangelist
3,p:5,c:3,Senior Director Strategic Alliances
4,p:7,c:4,Chief Executive Officer
5,p:8,c:4,Senior Software Engineer
6,p:9,c:4,Systems Engineering Manager
7,p:10,c:5,"Founder and CEO, Board Of Directors"
8,p:11,c:5,Co-Founder
9,p:12,c:5,"Chief Revenue Officer, VP of Operations"
10,p:13,c:5,VP of Product Management
11,p:14,c:5,Co-founder
12,p:16,c:7299,Founder and CEO
13,p:17,c:7299,Co-founder and CTO
14,p:18,c:7299,"SVP, Technology and Partnerships"
15,p:19,c:7299,"VP, Finance & Administration"
16,p:20,c:7299,"VP, Sales"
17,p:21,c:7299,"VP, Customer Service"
18,p:22,c:7299,"VP, Business Development"
19,p:23,c:7299,"VP, Engineering"
20,p:24,c:7299,"VP, Marketing"
21,p:25,c:7299,"VP, Product"
22,p:29,f:3,General Partner
23,p:30,c:9,Founder & Chairman
24,p:31,c:9,Board Member
25,p:26,f:6,Partner
26,p:32,f:6,Partner
27,p:33,f:6,Partner
28,p:34,f:6,Executive General Partner
29,p:35,f:7,General Partner
...,...,...,...
402847,p:268523,c:25744,Vice President of Sales - NextWave Wireless
402848,p:268523,c:230516,Director of Business Development - Marvell Sem...
402849,p:268523,c:4304,Director of UMTS Business Development
402850,p:268523,c:4304,Regional Manager UMTS Business Development
402851,p:268523,c:4304,OMAP Business Development Manager
402852,p:158143,c:12612,"President & CEO, Wolters Kluwer Health, Clinic..."
402853,p:268523,c:4304,Sales Account Manager
402854,p:268523,c:4304,Technical Sales Associate
402855,p:158143,c:218119,COO
402856,p:158143,c:1916,VP / GM positions - GE Information Services
402857,p:158143,c:1916,Sr. Product/Service Management positions - GE ...
402858,p:268524,c:286211,Managing Partner
402859,p:268524,c:286212,Managing Partner
402860,p:268524,c:4715,Engagement Manager
402861,p:268524,c:4715,Independent Management Consultant and An Engag...
402862,p:268524,c:286213,Chief Executive Officer
402863,p:268589,c:12612,"VP, Finance & Clinical Solutions"
402864,p:268590,c:286215,Co-Founder
402865,p:268592,c:256200,CEO
402866,p:268593,c:256200,COO
402867,p:268589,c:12612,Accounting Manager for Facts & Comparisons
402868,p:268589,c:12612,"Controller, Wolters Kluwer Health"
402869,p:268589,c:12612,"Director, Accounting - Professional & Educatio..."
402870,p:268527,c:39172,"Director, Business Development"
402871,p:268527,c:286217,"Sr. Manager, IP Analytics"
402872,p:268527,c:286218,Sr. Consultant/Patent Agent
402873,p:268597,c:12612,"VP, GM & Editor In Chief - Clinical Decison Su..."
402874,p:268528,c:286152,Vice President
402875,p:268528,c:286220,"General Counsel, Director of Patents and Licen..."
402876,p:268528,c:286221,Design Engineer

In [4]:
df_ppl = df_relationship.groupby(['relationship_object_id'],as_index=False).count()

df_ppl

       relationship_object_id  person_object_id  title
0                         c:1                17     17
1                        c:10                 6      6
2                       c:100                12     12
3                      c:1000                 1      1
4                     c:10002                 2      2
5                    c:100042                 1      1
6                     c:10005                 2      2
7                    c:100062                 2      2
8                     c:10009                 2      2
9                      c:1001                11      7
10                    c:10010                 1      1
11                    c:10011                 3      3
12                    c:10012                 1      1
13                    c:10013                 2      2
14                    c:10014                 9      6
15                    c:10015                14     14
16                   c:100155                 6      6
17                   c:100174                 2      2
18                   c:100178                 2      2
19                    c:10018                19     18
20                   c:100189                 2      2
21                     c:1002                 1      1
22                    c:10021                 2      0
23                   c:100212                 2      2
24                    c:10022                 3      3
25                   c:100230                 1      1
26                   c:100238                 2      2
27                    c:10024                 2      2
28                   c:100243                 4      4
29                   c:100253                 1      1
...                       ...               ...    ...
137259                 f:9944                 1      1
137260                 f:9949                 1      1
137261                 f:9950                 1      0
137262                 f:9953                 1      1
137263                 f:9954                 1      1
137264                 f:9958                 1      1
137265                  f:996                15     15
137266                 f:9960                 1      1
137267                 f:9964                 1      1
137268                 f:9965                 1      1
137269                 f:9966                 1      1
137270                 f:9968                 4      4
137271                 f:9969                 1      1
137272                  f:997                 2      1
137273                 f:9970                 4      4
137274                 f:9979                 1      1
137275                  f:998                28     25
137276                 f:9981                 1      1
137277                 f:9983                 1      1
137278                 f:9985                 1      1
137279                 f:9988                 1      1
137280                 f:9989                 3      3
137281                  f:999                 7      7
137282                 f:9990                 1      1
137283                 f:9992                 1      0
137284                 f:9993                 1      0
137285                 f:9994                 1      1
137286                 f:9995                 1      0
137287                 f:9996                 1      0
137288                 f:9999                 1      1

[137289 rows x 3 columns]

In [5]:
nltk.download('vader_lexicon')
sid = SentimentIntensityAnalyzer()
neg = df_relationship["title"].apply(lambda x :  sid.polarity_scores(str(x))["neg"]) 
compound = df_relationship["title"].apply(lambda x :  sid.polarity_scores(str(x))["compound"]) 
neu = df_relationship["title"].apply(lambda x :  sid.polarity_scores(str(x))["neu"]) 
pos = df_relationship["title"].apply(lambda x :  sid.polarity_scores(str(x))["pos"]) 

df_relationship["neg"] = neg
df_relationship["compound"] = compound
df_relationship["neu"] = neu
df_relationship["pos"] = pos

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/Abby/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [6]:
df_semantic = df_relationship.groupby(['relationship_object_id'],as_index=False).sum()

df_semantic

       relationship_object_id    neg  compound     neu    pos
0                         c:1  0.000    0.0000  17.000  0.000
1                        c:10  0.000    0.0000   6.000  0.000
2                       c:100  0.000    0.0000  12.000  0.000
3                      c:1000  0.000    0.0000   1.000  0.000
4                     c:10002  0.000    0.4404   1.256  0.744
5                    c:100042  0.000    0.0000   1.000  0.000
6                     c:10005  0.000    0.0000   2.000  0.000
7                    c:100062  0.000    0.0000   2.000  0.000
8                     c:10009  0.000    0.0000   2.000  0.000
9                      c:1001  0.000    0.0000  11.000  0.000
10                    c:10010  0.000    0.0000   1.000  0.000
11                    c:10011  0.000    0.0000   3.000  0.000
12                    c:10012  0.000    0.0000   1.000  0.000
13                    c:10013  0.000    0.0000   2.000  0.000
14                    c:10014  0.000    0.0000   9.000  0.000
15                    c:10015  0.000    0.0000  14.000  0.000
16                   c:100155  0.000    0.0000   6.000  0.000
17                   c:100174  0.000    0.0000   2.000  0.000
18                   c:100178  0.000    0.0000   2.000  0.000
19                    c:10018  0.231   -0.1280  18.769  0.000
20                   c:100189  0.000    0.0000   2.000  0.000
21                     c:1002  0.000    0.0000   1.000  0.000
22                    c:10021  0.000    0.0000   2.000  0.000
23                   c:100212  0.000    0.0000   2.000  0.000
24                    c:10022  0.000    0.0000   3.000  0.000
25                   c:100230  0.000    0.0000   1.000  0.000
26                   c:100238  0.000    0.0000   2.000  0.000
27                    c:10024  0.000    0.0000   2.000  0.000
28                   c:100243  0.000    0.0000   4.000  0.000
29                   c:100253  0.000    0.0000   1.000  0.000
...                       ...    ...       ...     ...    ...
137259                 f:9944  0.000    0.0000   1.000  0.000
137260                 f:9949  0.000    0.0000   1.000  0.000
137261                 f:9950  0.000    0.0000   1.000  0.000
137262                 f:9953  0.000    0.0000   1.000  0.000
137263                 f:9954  0.000    0.0000   1.000  0.000
137264                 f:9958  0.000    0.0000   1.000  0.000
137265                  f:996  0.000    0.0000  15.000  0.000
137266                 f:9960  0.000    0.0000   1.000  0.000
137267                 f:9964  0.000    0.0000   1.000  0.000
137268                 f:9965  0.000    0.0000   1.000  0.000
137269                 f:9966  0.000    0.0000   1.000  0.000
137270                 f:9968  0.000    0.0000   4.000  0.000
137271                 f:9969  0.000    0.0000   1.000  0.000
137272                  f:997  0.000    0.0000   2.000  0.000
137273                 f:9970  0.000    0.0000   4.000  0.000
137274                 f:9979  0.000    0.0000   1.000  0.000
137275                  f:998  0.000    0.0000  28.000  0.000
137276                 f:9981  0.000    0.0000   1.000  0.000
137277                 f:9983  0.000    0.0000   1.000  0.000
137278                 f:9985  0.000    0.0000   1.000  0.000
137279                 f:9988  0.000    0.0000   1.000  0.000
137280                 f:9989  0.000    0.0000   3.000  0.000
137281                  f:999  0.000    0.0000   7.000  0.000
137282                 f:9990  0.000    0.0000   1.000  0.000
137283                 f:9992  0.000    0.0000   1.000  0.000
137284                 f:9993  0.000    0.0000   1.000  0.000
137285                 f:9994  0.000    0.0000   1.000  0.000
137286                 f:9995  0.000    0.0000   1.000  0.000
137287                 f:9996  0.000    0.0000   1.000  0.000
137288                 f:9999  0.000    0.0000   1.000  0.000

[137289 rows x 5 columns]

In [9]:
df = pd.merge(df_semantic, df_ppl, how='inner' ,left_on="relationship_object_id", right_on="relationship_object_id")
df = df.iloc[:,[0,1,2,3,4,5]] 
df.rename(columns={"person_object_id":"employees"},inplace=True)
df["employees"] = normalize(df["employees"])
df

/Users/Abby/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

       relationship_object_id    neg  compound     neu    pos  employees
0                         c:1  0.000    0.0000  17.000  0.000   0.013594
1                        c:10  0.000    0.0000   6.000  0.000   0.004248
2                       c:100  0.000    0.0000  12.000  0.000   0.009346
3                      c:1000  0.000    0.0000   1.000  0.000   0.000000
4                     c:10002  0.000    0.4404   1.256  0.744   0.000850
5                    c:100042  0.000    0.0000   1.000  0.000   0.000000
6                     c:10005  0.000    0.0000   2.000  0.000   0.000850
7                    c:100062  0.000    0.0000   2.000  0.000   0.000850
8                     c:10009  0.000    0.0000   2.000  0.000   0.000850
9                      c:1001  0.000    0.0000  11.000  0.000   0.008496
10                    c:10010  0.000    0.0000   1.000  0.000   0.000000
11                    c:10011  0.000    0.0000   3.000  0.000   0.001699
12                    c:10012  0.000    0.0000   1.000  0.000   0.000000
13                    c:10013  0.000    0.0000   2.000  0.000   0.000850
14                    c:10014  0.000    0.0000   9.000  0.000   0.006797
15                    c:10015  0.000    0.0000  14.000  0.000   0.011045
16                   c:100155  0.000    0.0000   6.000  0.000   0.004248
17                   c:100174  0.000    0.0000   2.000  0.000   0.000850
18                   c:100178  0.000    0.0000   2.000  0.000   0.000850
19                    c:10018  0.231   -0.1280  18.769  0.000   0.015293
20                   c:100189  0.000    0.0000   2.000  0.000   0.000850
21                     c:1002  0.000    0.0000   1.000  0.000   0.000000
22                    c:10021  0.000    0.0000   2.000  0.000   0.000850
23                   c:100212  0.000    0.0000   2.000  0.000   0.000850
24                    c:10022  0.000    0.0000   3.000  0.000   0.001699
25                   c:100230  0.000    0.0000   1.000  0.000   0.000000
26                   c:100238  0.000    0.0000   2.000  0.000   0.000850
27                    c:10024  0.000    0.0000   2.000  0.000   0.000850
28                   c:100243  0.000    0.0000   4.000  0.000   0.002549
29                   c:100253  0.000    0.0000   1.000  0.000   0.000000
...                       ...    ...       ...     ...    ...        ...
137259                 f:9944  0.000    0.0000   1.000  0.000   0.000000
137260                 f:9949  0.000    0.0000   1.000  0.000   0.000000
137261                 f:9950  0.000    0.0000   1.000  0.000   0.000000
137262                 f:9953  0.000    0.0000   1.000  0.000   0.000000
137263                 f:9954  0.000    0.0000   1.000  0.000   0.000000
137264                 f:9958  0.000    0.0000   1.000  0.000   0.000000
137265                  f:996  0.000    0.0000  15.000  0.000   0.011895
137266                 f:9960  0.000    0.0000   1.000  0.000   0.000000
137267                 f:9964  0.000    0.0000   1.000  0.000   0.000000
137268                 f:9965  0.000    0.0000   1.000  0.000   0.000000
137269                 f:9966  0.000    0.0000   1.000  0.000   0.000000
137270                 f:9968  0.000    0.0000   4.000  0.000   0.002549
137271                 f:9969  0.000    0.0000   1.000  0.000   0.000000
137272                  f:997  0.000    0.0000   2.000  0.000   0.000850
137273                 f:9970  0.000    0.0000   4.000  0.000   0.002549
137274                 f:9979  0.000    0.0000   1.000  0.000   0.000000
137275                  f:998  0.000    0.0000  28.000  0.000   0.022940
137276                 f:9981  0.000    0.0000   1.000  0.000   0.000000
137277                 f:9983  0.000    0.0000   1.000  0.000   0.000000
137278                 f:9985  0.000    0.0000   1.000  0.000   0.000000
137279                 f:9988  0.000    0.0000   1.000  0.000   0.000000
137280                 f:9989  0.000    0.0000   3.000  0.000   0.001699
137281                  f:999  0.000    0.0000   7.000  0.000   0.005098
137282                 f:9990  0.000    0.0000   1.000  0.000   0.000000
137283                 f:9992  0.000    0.0000   1.000  0.000   0.000000
137284                 f:9993  0.000    0.0000   1.000  0.000   0.000000
137285                 f:9994  0.000    0.0000   1.000  0.000   0.000000
137286                 f:9995  0.000    0.0000   1.000  0.000   0.000000
137287                 f:9996  0.000    0.0000   1.000  0.000   0.000000
137288                 f:9999  0.000    0.0000   1.000  0.000   0.000000

[137289 rows x 6 columns]

In [10]:
df_unique_funding = pd.read_pickle('./merge_pkl/funding.pkl')

df = pd.merge(df_unique_funding.iloc[:,[0]], df, how="left",left_on="funding_object_id", right_on="relationship_object_id" )

df.drop(columns=["relationship_object_id"], inplace=True)
df.fillna(0, inplace=True)

df

      funding_object_id  neg  compound      neu    pos  employees
0              c:144040  0.0    0.0000    1.000  0.000   0.000000
1               c:18038  0.0    0.0000   11.000  0.000   0.008496
2              c:161452  0.0    0.0000    3.000  0.000   0.001699
3              c:161453  0.0    0.0000    2.000  0.000   0.000850
4              c:161480  0.0    0.0000    4.000  0.000   0.002549
5              c:264245  0.0    0.0000    1.000  0.000   0.000000
6               c:18202  0.0    0.0000    1.000  0.000   0.000000
7               c:51578  0.0    0.0000    3.000  0.000   0.001699
8              c:161699  0.0    0.0000    1.000  0.000   0.000000
9              c:161944  0.0    0.5719    4.448  0.552   0.003398
10               c:4299  0.0    0.0000    1.000  0.000   0.000000
11             c:263989  0.0    0.0000    2.000  0.000   0.000850
12              c:68549  0.0    0.0000    0.000  0.000   0.000000
13              c:68486  0.0    0.0000    0.000  0.000   0.000000
14              c:68442  0.0    0.0000    2.000  0.000   0.000850
15             c:162067  0.0    0.0000    2.000  0.000   0.000850
16              c:18701  0.0    0.0000    4.000  0.000   0.002549
17              c:18741  0.0    0.0000    3.000  0.000   0.001699
18             c:264553  0.0    0.1280    2.727  0.273   0.001699
19              c:68329  0.0    0.0000    2.000  0.000   0.000850
20              c:45196  0.0    0.0000    0.000  0.000   0.000000
21              c:69063  0.0    0.0000    1.000  0.000   0.000000
22             c:265497  0.0    0.0000    2.000  0.000   0.000850
23             c:161240  0.0    0.0000   11.000  0.000   0.008496
24             c:265463  0.0    0.0000    1.000  0.000   0.000000
25              c:64996  0.0    0.0000    2.000  0.000   0.000850
26              c:17758  0.0    0.0000   16.000  0.000   0.012744
27             c:265370  0.0    0.0000    2.000  0.000   0.000850
28              c:69596  0.0    0.0000    6.000  0.000   0.004248
29             c:265241  0.0    0.0000    1.000  0.000   0.000000
...                 ...  ...       ...      ...    ...        ...
16748          c:261056  0.0    0.0000    1.000  0.000   0.000000
16749          c:266200  0.0    0.0000    2.000  0.000   0.000850
16750          c:145945  0.0    0.0000    3.000  0.000   0.001699
16751           c:59556  0.0    0.0000    4.000  0.000   0.002549
16752          c:220572  0.0    0.0000    4.000  0.000   0.002549
16753          c:243852  0.0    0.0000    2.000  0.000   0.000850
16754           c:69136  0.0    0.0000    1.000  0.000   0.000000
16755          c:212776  0.0    0.0000    0.000  0.000   0.000000
16756          c:244910  0.0    0.0000    2.000  0.000   0.000850
16757           c:16243  0.0    0.0000    1.000  0.000   0.000000
16758          c:277196  0.0    0.0000    1.000  0.000   0.000000
16759            c:6713  0.0    0.0000   20.000  0.000   0.016143
16760          c:245323  0.0    0.0000    1.000  0.000   0.000000
16761           c:35691  0.0    0.0000    0.000  0.000   0.000000
16762          c:219131  0.0    0.0000    2.000  0.000   0.000850
16763          c:267819  0.0    0.0000    2.000  0.000   0.000850
16764          c:177075  0.0    0.0000    0.000  0.000   0.000000
16765          c:144811  0.0    0.0000    6.000  0.000   0.004248
16766           c:36848  0.0    0.0000   18.000  0.000   0.014444
16767          c:164565  0.0    0.0000    2.000  0.000   0.000850
16768          c:279000  0.0    0.0000    1.000  0.000   0.000000
16769            c:8261  0.0    0.7988   54.256  0.744   0.045879
16770          c:236502  0.0    0.0000    0.000  0.000   0.000000
16771          c:269551  0.0    0.0000    0.000  0.000   0.000000
16772           c:34590  0.0    0.0000   42.000  0.000   0.034834
16773           c:42841  0.0    0.0000    2.000  0.000   0.000850
16774           c:25993  0.0    0.0000    2.000  0.000   0.000850
16775            c:4304  0.0    1.0753  139.611  1.389   0.118946
16776          c:266692  0.0    0.0000    0.000  0.000   0.000000
16777          c:228200  0.0    0.0000    1.000  0.000   0.000000

[16778 rows x 6 columns]

In [20]:
X_static = df.iloc[:,1:].values
#X_static = np.tile(X_static, (1,226,1)).reshape(-1,226,5)

In [21]:
np.save("X_static", X_static)

In [22]:
X = np.load("X_static.npy")

In [23]:
X.shape

(16778, 5)